services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=syncstudio
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d syncstudio" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    ports:
#      - "5432:5432"

  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://postgres:postgres@db:5432/syncstudio?sslmode=disable
      - up
    depends_on:
      db:
         condition: service_healthy

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
